org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
modelBaseUrl=https://pub-930c1a4dd58b4db481420ab72789dbd8.r2.dev/
inferenceApiUrl=http://34.238.98.220:8080
contributeUrl=http://34.238.98.220:8090
